# Kubernetes Secrets Configuration
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
stringData:
  db-host: 'mysql-service'
  db-name: 'backend_db'
  db-user: 'backend_user'
  db-pass: 'your_secure_password_here'
  jwt-secret: 'your_super_secure_jwt_secret_key_here'
  redis-host: 'redis-service'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  NODE_ENV: 'production'
  PORT: '3000'
  DB_PORT: '3306'
  REDIS_PORT: '6379'
  API_PREFIX: '/api/v1'
  LOG_LEVEL: 'info'

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
